# SwiftLint Configuration for Clnbrd
# macOS clipboard cleaning utility

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - last_where
  - reduce_into
  - redundant_nil_coalescing
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

included:
  - Clnbrd/Clnbrd

excluded:
  - Carthage
  - Clnbrd/Clnbrd/Documentation
  - Documentation
